// Centralized component exports for better organization
export { default as UnifiedPopularityMetrics } from './unified-popularity-metrics';
export { EventCard } from './event-card';
export { TicketCard } from './ticket-card';
export { SearchBar } from './search-bar';
export { FilterDropdown } from './filter-dropdown';
export { VenueMap } from './venue-map';
export { TicketVerification } from './ticket-verification';
export { MobileNav } from './mobile-nav';
export { PullToRefresh } from './pull-to-refresh';
export { RealTimeNotifications } from './real-time-notifications';
export { GlobalMarketplaceStats } from './global-marketplace-stats';
export { TrustScoreMeter } from './trust-score-meter';
export { VerificationBadge } from './verification-badge';
export { SocialShare } from './social-share';
export { ErrorBoundary } from './error-boundary';
export { EventAtmosphere } from './event-atmosphere';
export { TicketHeatMap } from './ticket-heatmap';
export { EventRecommendations } from './event-recommendations';
export { TicketComparison } from './ticket-comparison';
export { SearchHints } from './search-hints';

// Modal exports
export { ContactRequestModal } from './contact-request-modal';
export { SellerProfileModal } from './seller-profile-modal';
export { SellerDetailsModal } from './seller-details-modal';
export { TicketDetailModal } from './ticket-detail-modal';
export { DisputeModal } from './dispute-modal';
export { VerificationModal } from './verification-modal';
export { AIVerificationModal } from './ai-verification-modal';

// SEO Components (consolidated)
export { default as SEO } from './seo';
export { HelmetProvider } from './helmet-manager';
export { CanonicalUrlManager } from './canonical-url-manager';
export { InternationalSEO } from './international-seo';
export { default as EnhancedSEO } from './enhanced-seo';
export { default as AdvancedStructuredData } from './advanced-structured-data';

// UI Components
export * from './ui/button';
export * from './ui/card';
export * from './ui/input';
export * from './ui/label';
export * from './ui/select';
export * from './ui/textarea';
export * from './ui/checkbox';
export * from './ui/radio-group';
export * from './ui/switch';
export * from './ui/slider';
export * from './ui/progress';
export * from './ui/badge';
export * from './ui/alert';
export * from './ui/dialog';
export * from './ui/popover';
export * from './ui/dropdown-menu';
export * from './ui/navigation-menu';
export * from './ui/tabs';
export * from './ui/accordion';
export * from './ui/separator';
export * from './ui/scroll-area';
export * from './ui/toast';
export * from './ui/toaster';
export * from './ui/tooltip';
export * from './ui/hover-card';
export * from './ui/alert-dialog';
export * from './ui/context-menu';
export * from './ui/menubar';
export * from './ui/avatar';
export * from './ui/calendar';
export * from './ui/form';
export * from './ui/table';
export * from './ui/collapsible';
export * from './ui/aspect-ratio';
export * from './ui/toggle';
export * from './ui/toggle-group';
export * from './ui/resizable';
export * from './ui/drawer';
export * from './ui/pagination';
export * from './ui/breadcrumb';
export * from './ui/command';
export * from './ui/sheet';
export * from './ui/skeleton';
export * from './ui/navigation';
export * from './ui/footer';
export * from './ui/page-transition';